### ISSUE TITLE
Script Hangs

### ISSUE THREAD

**Issue by TechJeeper** [keithprickett/lacrosse_to_wunderground#1]
When I run the python script it just hangs.  Do you have a list of dependencies?

**Comment by keithprickett** [comment]
@TechJeeper you'll need the other two repos from my github: https://github.com/keithprickett/lacrosse_weather and https://github.com/keithprickett/wunderground_uploader

I expect you'd get a different error than "it just hangs" if you didn't have those already though.  Is there any output associated with your "hang?"

**Comment by keithprickett** [comment]
No response in months.

**Comment by bblboy54** [comment]
I'm trying to set this up and I'm actually getting the same exact thing.... When I run the script it just hangs and does nothing until I ctrl-c it....  Once I hit ctrl-c it returns a trace:

```
root@martha:~/myweather# python3 ./lacrosse_to_wunderground.py 
Warning: Didn't get latest observation time, loading from time 0
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lacrosse_to_wunderground.py", line 85, in <module>
    push_all_since_timestamp_temperature_to_wunderground(w, old_utc_timestamp)
  File "./lacrosse_to_wunderground.py", line 50, in push_all_since_timestamp_temperature_to_wunderground
    wunderground_upload_data_point(station_id, station_key, weather_data, utc_timestamp)
  File "/root/myweather/wunderground_uploader/uploader.py", line 49, in wunderground_upload_data_point
    requests.get('http://rtupdate.wunderground.com/weatherstation/updateweatherstation.php', params=payload)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1224, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 390, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 352, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

I get a slightly different trace when using the full command you specify in the readme

```
root@martha:~/myweather# cd ~/myweather && python3 ./lacrosse_to_wunderground.py `cat myweather_ts` > myweather_ts
^CTraceback (most recent call last):
  File "./lacrosse_to_wunderground.py", line 85, in <module>
    push_all_since_timestamp_temperature_to_wunderground(w, old_utc_timestamp)
  File "./lacrosse_to_wunderground.py", line 50, in push_all_since_timestamp_temperature_to_wunderground
    wunderground_upload_data_point(station_id, station_key, weather_data, utc_timestamp)
  File "/root/myweather/wunderground_uploader/uploader.py", line 49, in wunderground_upload_data_point
    requests.get('http://rtupdate.wunderground.com/weatherstation/updateweatherstation.php', params=payload)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1142, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1180, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1138, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 154, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

I've tried letting the process run for 5+ mins but nothing ever seems to happen.  There also isn't any increased load on the system but I do see that the python3 command does remain running in ps ax:

` 6870 pts/0    S+     0:00 python3 ./lacrosse_to_wunderground.py 0
`
