### ISSUE TITLE
Script Hang

### ISSUE THREAD

**Issue by bblboy54** [keithprickett/lacrosse_to_wunderground#3]
I updated a previous issue but after I did so I realized the issue was closed so I'm putting the information here as well.  There is some additional information from last night.

The issue that I'm having is when I run the script it's just hanging and seemingly not doing anything at all.  I don't get any feedback at all until I ctrl-c the task which then gives me a trace.  I've left the script run overnight and it's still sitting and seemingly not doing anything....  I did, however, noticed that there is some updated information being sent to Weather Underground.  I started the script last at 3:05am local time and now on the wunderground page for the weather station there is temperature history for the last 5 days up until 3:04am (one min before I started the script).

Here is the output after ctrl-c from running for 8 hours:
```
root@martha:~/myweather# cd ~/myweather && python3 ./lacrosse_to_wunderground.py `cat myweather_ts` > myweather_ts

^CTraceback (most recent call last):
  File "./lacrosse_to_wunderground.py", line 95, in <module>
    push_all_since_timestamp_wind_to_wunderground(w, old_utc_timestamp)
  File "./lacrosse_to_wunderground.py", line 62, in push_all_since_timestamp_wind_to_wunderground
    time.sleep(2.5)
KeyboardInterrupt
```
Here are two previous iterations where I ran the script and terminated it after 5 mins or so:

```
root@martha:~/myweather# python3 ./lacrosse_to_wunderground.py 
Warning: Didn't get latest observation time, loading from time 0
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lacrosse_to_wunderground.py", line 85, in <module>
    push_all_since_timestamp_temperature_to_wunderground(w, old_utc_timestamp)
  File "./lacrosse_to_wunderground.py", line 50, in push_all_since_timestamp_temperature_to_wunderground
    wunderground_upload_data_point(station_id, station_key, weather_data, utc_timestamp)
  File "/root/myweather/wunderground_uploader/uploader.py", line 49, in wunderground_upload_data_point
    requests.get('http://rtupdate.wunderground.com/weatherstation/updateweatherstation.php', params=payload)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1224, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 390, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 352, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

```
root@martha:~/myweather# cd ~/myweather && python3 ./lacrosse_to_wunderground.py `cat myweather_ts` > myweather_ts
^CTraceback (most recent call last):
  File "./lacrosse_to_wunderground.py", line 85, in <module>
    push_all_since_timestamp_temperature_to_wunderground(w, old_utc_timestamp)
  File "./lacrosse_to_wunderground.py", line 50, in push_all_since_timestamp_temperature_to_wunderground
    wunderground_upload_data_point(station_id, station_key, weather_data, utc_timestamp)
  File "/root/myweather/wunderground_uploader/uploader.py", line 49, in wunderground_upload_data_point
    requests.get('http://rtupdate.wunderground.com/weatherstation/updateweatherstation.php', params=payload)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1142, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1180, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1138, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 154, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```
In all cases the python command remains running and periodically shows a very very small amount of CPU in top (less than 1) but there is never any heavy usage.  When looking at ps ax it shows the task is running...... but here's something interesting that I noticed.  The first time I ran the script after echoing 0 into myweather_ts it shows that 0 on the command line in ps ax:
` 6870 pts/0    S+     0:00 python3 ./lacrosse_to_wunderground.py 0
`
But when I run it again, this is what I see:
` 8553 pts/2    S+     0:00 python3 ./lacrosse_to_wunderground.py Warning: Didn't get latest observation time, loading from time 0`

I'm guessing that is the result of previous output being redirected to the myweather_ts file. After echoing 0 again we're back at the 0:
` 8591 pts/2    S+     0:00 python3 ./lacrosse_to_wunderground.py 0`

But still, the script seems to hang but so far after 3 mins of the script running I'm not seeing any information updates on the wunderground page (3:04am is still the last reading).  I don't know at what point that data actually arrived at wunderground overnight and why it took a while to do so.

**Comment by bblboy54** [comment]
FWIW, the script has been running on my server for about 7 hours and there is new data on wunderground again up until the time that I started the script running....  I know that the data did not make it to wunderground within the first half hour of the script running but I wasn't able to keep checking the site beyond that until just now.  The script is still currently running:
`8591 pts/2    S+     0:22 python3 ./lacrosse_to_wunderground.py 0`

Also, I did want to note that I did edit the script to reflect the name differences for temperature and wind to that which the sensors are named.  The wind sensor is named "Roof" and the temperature is named "Side Porch" but I first used the print line that you referenced in the script to find out that the formatting of those coming from lacross is "roof" and "side_porch" and I put those values in place.

Here is the edited section of the lacross_to_wunderground.py file:
```
    token = lacrosse_login(email, password)
    locations = lacrosse_get_locations(token)
    devices = lacrosse_get_devices(token, locations)
    new_timestamp = old_utc_timestamp
    try:
        for device in devices:
            # TODO Will need updated credentials if we do long operations
            # Your 'device_name' is likely different than 'temperature'
            # replace this name with something that has an external "Temperature"
            # sensor
            # doing the following can show you the name here:
            #  print(device['device_name'])
            # Same below with 'wind'
            if device['device_name'] == 'side_porch':
                w = lacrosse_get_weather_data(token, device)
                push_all_since_timestamp_temperature_to_wunderground(w, old_utc_timestamp)
                new_timestamp = w['Temperature']['values'][-1]['u']

        # Do this twice, as long pushes agove may cause credentials to expire
        token = lacrosse_login(email, password)
        locations = lacrosse_get_locations(token)
        devices = lacrosse_get_devices(token, locations)
        for device in devices:
            if device['device_name'] == 'roof':
                w = lacrosse_get_weather_data(token, device)
                push_all_since_timestamp_wind_to_wunderground(w, old_utc_timestamp)
    except Exception:
        # Ignore all errors, just retry again later with your automation
        pass

```
I'm going to continue to let the script run and see what happens.  Currently the myweather_ts file is empty (it seems to only populate with the Warning message whenever I terminate the script.

**Comment by keithprickett** [comment]
bblboy54 - I suspect things are working correctly.  The script can take a long time when starting from time 0.  Also, wunderground displaying the data is often delayed, significantly.  You shouldn't expect to see data uploaded immediately after it's uploaded from the script on wunderground.  

One thing to try is to use a timestamp other than 0 that is much more recent in the future.  There is no script output -- so I admit it is difficult to see if something is happening or not.  One thing you could do if you want to monitor is to add some debug / print statements.
